# Docker Compose configuration for Government Invoice Form
version: "3.8"

services:
  # Web development service
  web-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  # Web production service
  web-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "80:80"
    networks:
      - app-network

  # Android build service
  android-builder:
    build:
      context: .
      dockerfile: Dockerfile.android
      target: android-builder
    volumes:
      - ./android/app/build/outputs:/app/android/app/build/outputs
      - android-cache:/app/android/.gradle
    environment:
      - ANDROID_HOME=/opt/android-sdk
      - JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
    networks:
      - app-network

  # Android development environment
  android-dev:
    build:
      context: .
      dockerfile: Dockerfile.android
      target: android-dev
    volumes:
      - .:/app
      - /app/node_modules
      - android-cache:/app/android/.gradle
      - android-sdk:/opt/android-sdk
    environment:
      - ANDROID_HOME=/opt/android-sdk
      - JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
    stdin_open: true
    tty: true
    networks:
      - app-network
    ports:
      - "5173:5173" # For web dev server
      - "8080:8080" # For Android debugging

volumes:
  android-cache:
    driver: local
  android-sdk:
    driver: local

networks:
  app-network:
    driver: bridge
